export default {
  buddha: require('../assets/images/buddha.png'),
  wheel: require('../assets/images/dhamma-wheel.png'),
  dhammaWheel: require('../assets/images/dhamma.png'),
  sayadaw1: require('../assets/images/phaauk.jpeg'),
  sayadaw2: require('../assets/images/thidagu.jpeg'),
  sayadaw3: require('../assets/images/venNDML.jpeg'),
  sayadaw4: require('../assets/images/tsss.jpeg'),
  sayadaw5: require('../assets/images/uztk.jpg'),
  sayadaw6: require('../assets/images/phyu.jpeg'),
  sayadaw7: require('../assets/images/cmrm.jpeg'),
  sayadaw8: require('../assets/images/u_thunanda.jpeg'),
  sayadaw9: require('../assets/images/myaukU.jpeg'),
  sayadaw10: require('../assets/images/uKovida.jpeg'),
  sayadaw11: require('../assets/images/uPonnyar.jpeg'),
  sayadaw12: require('../assets/images/kyarNiKan.jpeg'),
  sayadaw13: require('../assets/images/delohh.jpeg'),
  // mom: require('../assets/images/momom.png'),
};
